import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  outputFileTracingRoot: path.join(__dirname),
  turbopack: {
    root: __dirname,
  },
  outputFileTracingIncludes: {
    '/api/figures': ['historyrank.db'],
    '/api/figures/[id]': ['historyrank.db'],
    '/api/scatter': ['historyrank.db'],
    '/api/health': ['historyrank.db'],
    '/api/media': [
      'data/raw/media/ucsc-history-media.jsonl',
      'data/raw/media/*.json',
      'data/media-figure-links.suggestions.json',
      'data/cache/media-details.json',
      'data/embeddings/media.json',
    ],
  },
  outputFileTracingExcludes: {
    '/api/figures': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/figures/[id]': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/scatter': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/compare': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/benchmarks': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/benchmarks/[model]': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/map': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/media': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/lists': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/export': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/wikipedia': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
    '/api/health': [
      'public/thumbnails/**',
      'public/media-thumbnails/**',
      'data/raw/media/**',
      '**/*.jpg',
      '**/*.png',
      '**/*.webp',
      'literary canon ui example.jpg',
      'ui example currently.jpg',
      'perplexity example.jpg',
      'perplexity font.jpg',
    ],
  },
};

export default nextConfig;
